version: '3.11'

services:
  app_api:

    platform: linux/amd64
    build:
      context: .

    command: sh -c "gunicorn -b :5000 -w 4 --chdir app/ app:app"

    tty: false
    restart: on-failure

    ports:
      - "8000:5000"

    env_file:
      - .env

    depends_on: [mongodb]

  mongodb:
    image: mongodb/mongodb-community-server

    environment:
      MONGO_INITDB_DATABASE: ${db_name}
      MONGO_INITDB_ROOT_USERNAME: ${db_user}
      MONGO_INITDB_ROOT_PASSWORD: ${db_pass}
    env_file:
      - .env

    volumes:
      - mongo_data_safe_secret:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


volumes:
  mongo_data_safe_secret:
